# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_COMP_Z <- function(moment, nu, lambda, maxn) {
    .Call('spaMM_Rcpp_COMP_Z', PACKAGE = 'spaMM', moment, nu, lambda, maxn)
}

Rcpp_pMVN <- function(L, limits, ismax, rand_seq, nrep) {
    .Call('spaMM_Rcpp_pMVN', PACKAGE = 'spaMM', L, limits, ismax, rand_seq, nrep)
}

Rcpp_gibbs_iter <- function(fix, y, lambda, n_u_h, randbGivenObs, ZAisI, eps, CondNorm, ZA, forV, LHSCorrblob, condL) {
    .Call('spaMM_Rcpp_gibbs_iter', PACKAGE = 'spaMM', fix, y, lambda, n_u_h, randbGivenObs, ZAisI, eps, CondNorm, ZA, forV, LHSCorrblob, condL)
}

Rcpp_gibbs_debug <- function(fix, y, decomp, estimCARrho, lambda, n_u_h, randbGivenObs, ZAisI, eps, CondNorm, ZA, forV, LHSCorrblob, condL) {
    .Call('spaMM_Rcpp_gibbs_debug', PACKAGE = 'spaMM', fix, y, decomp, estimCARrho, lambda, n_u_h, randbGivenObs, ZAisI, eps, CondNorm, ZA, forV, LHSCorrblob, condL)
}

Rcpp_gibbs <- function(ngibbs, gibbsSample, estimCARrho, decomp, fix, y, lambda, n_u_h, ZAisI, eps, CondNorm, ZA, forV, LHSCorrblob, condL) {
    .Call('spaMM_Rcpp_gibbs', PACKAGE = 'spaMM', ngibbs, gibbsSample, estimCARrho, decomp, fix, y, lambda, n_u_h, ZAisI, eps, CondNorm, ZA, forV, LHSCorrblob, condL)
}

lmwithQ <- function(XX, yy) {
    .Call('spaMM_lmwithQ', PACKAGE = 'spaMM', XX, yy)
}

leverages <- function(XX) {
    .Call('spaMM_leverages', PACKAGE = 'spaMM', XX)
}

Rcpp_qr_Q <- function(XX) {
    .Call('spaMM_Rcpp_qr_Q', PACKAGE = 'spaMM', XX)
}

Rcpp_QR <- function(XX) {
    .Call('spaMM_Rcpp_QR', PACKAGE = 'spaMM', XX)
}

sweepZ1W <- function(ZZ, WW) {
    .Call('spaMM_sweepZ1W', PACKAGE = 'spaMM', ZZ, WW)
}

ZWZt <- function(ZZ, WW) {
    .Call('spaMM_ZWZt', PACKAGE = 'spaMM', ZZ, WW)
}

ZtWZ <- function(ZZ, WW) {
    .Call('spaMM_ZtWZ', PACKAGE = 'spaMM', ZZ, WW)
}

Rcpp_Sig <- function(ZZ, WA, WB) {
    .Call('spaMM_Rcpp_Sig', PACKAGE = 'spaMM', ZZ, WA, WB)
}

Rcpp_d2hdv2 <- function(ZZ, WA, WB) {
    .Call('spaMM_Rcpp_d2hdv2', PACKAGE = 'spaMM', ZZ, WA, WB)
}

RcppChol <- function(AA) {
    .Call('spaMM_RcppChol', PACKAGE = 'spaMM', AA)
}

crossprodCpp <- function(Mat) {
    .Call('spaMM_crossprodCpp', PACKAGE = 'spaMM', Mat)
}

tcrossprodCpp <- function(Mat) {
    .Call('spaMM_tcrossprodCpp', PACKAGE = 'spaMM', Mat)
}

pseudoSolvediag <- function(XX, bb) {
    .Call('spaMM_pseudoSolvediag', PACKAGE = 'spaMM', XX, bb)
}

LevenbergMsolveCpp <- function(AA, rrhhss, dd) {
    .Call('spaMM_LevenbergMsolveCpp', PACKAGE = 'spaMM', AA, rrhhss, dd)
}

LogAbsDetCpp <- function(AA) {
    .Call('spaMM_LogAbsDetCpp', PACKAGE = 'spaMM', AA)
}

selfAdjointSolverCpp <- function(AA) {
    .Call('spaMM_selfAdjointSolverCpp', PACKAGE = 'spaMM', AA)
}

LevPerturbedQCpp <- function(perturbedwAugX, pforREML, RpRu, RpRd, lamOverLam0, phiOverPhi0) {
    .Call('spaMM_LevPerturbedQCpp', PACKAGE = 'spaMM', perturbedwAugX, pforREML, RpRu, RpRd, lamOverLam0, phiOverPhi0)
}

zrnorm <- function(n) {
    .Call('spaMM_zrnorm', PACKAGE = 'spaMM', n)
}

